### AQUI ESTARÁN LOS ENDPOINTS DE LA API PARA RECUPERAR LOS DATOS SEGUN LA URL

### RECUPERAR EL DASHBOARD
GET http://localhost:3128/api/dashboard

### RECUPERAR VISTA GESTION DE PLANES
GET http://localhost:3128/api/gestion/1

### CREAR NUEVO PLAN INVERSION Y PERIODO INICIAL
POST http://localhost:3128/api/gestion-modal

### OBTENER TODOS LOS PLANES DE CUENTA PARA EL MODAL
GET http://localhost:3128/api/gestion-modal

### OBTENER SUBCATEGORIAS SEGUN EL ID DE PLAN DE CUENTA
GET http://localhost:3128/api/gestion/modal/plancuenta-subcategoria/1

### LLENADO DE TABLAS PLAN INVERSION | PLAN INVERSION PLAN CUENTA | PLAN INVERSION SUBCATEGORIAS
POST http://localhost:3128/api/gestion/modal/plan-inversion

### OBTERNER SOLICITUDES SEGUN EL PERIODO ID SELECCIONADO
GET http://localhost:3128/api/periodo-SolicitudesList/1

### OBTENER DENTRO DEL MODAL LOS PLANES DE CUENTA SEGUN EL PIPC PARA CREAR UNA SOLICITUD
GET http://localhost:3128/api/periodo/solicitud

### CREAR SOLICITUD
POST http://localhost:3128/api/periodo/solicitud-crearsolicitud

### CREAR ARTICULOS Y ADJUNTARLO A SOLICITUD
POST http://localhost:3128/api/periodo/solicitud-addArticle/2

### AÑADIR SOPORTE INFO A SOLICITUD
POST http://localhost:3128/api/periodo/solicitud-soporte/2
Content-Type: application/json

{
 "FacturaURL": "https://drive.google.com/file/d/1OE--pZ_7vBmybSNFtsbP6MzZFFCiCpqB/view?usp=drive_link", 

 "CartaPyRURL":  "https://drive.google.com/file/d/1EZDqKklBYat6jQe4PEldS7klcw3VwPPe/view?usp=drive_link",

 "MontoFactura": 1687.20,

 "TipoMoneda": 2
 }

### OBTENER SOPORTE INFO DE SOLICITUD
GET http://localhost:3128/api/periodo/solicitud-soporte/2