### AQUI ESTARÁN LOS ENDPOINTS DE LA API PARA RECUPERAR LOS DATOS SEGUN LA URL

### RECUPERAR EL DASHBOARD
GET http://localhost:3128/api/dashboard

### RECUPERAR VISTA GESTION DE PLANES
GET http://localhost:3128/api/gestion/3

### OBTENER TODOS LOS PLANES DE CUENTA PARA EL MODAL
GET http://localhost:3128/api/gestion-modal

### OBTENER SUBCATEGORIAS SEGUN EL ID DE PLAN DE CUENTA
GET http://localhost:3128/api/gestion/modal/plancuenta-subcategoria/1

### LLENADO DE TABLAS PLAN INVERSION | PLAN INVERSION PLAN CUENTA | PLAN INVERSION SUBCATEGORIAS

